# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Remove old builds
          command: |
            rm -rf assets/ styles/
            # Ignore errors if doesn't exist
            rm index.html 2> /dev/null

      - run:
          name: Build files
          command: yarn deploy

      - run:
          name: Deploy files to GitHub
          command: |
            # Set Git username if not already set
            ./set_git_username.sh

            git add .
            git commit -m "Update site (`date '+%F %T %Z'`) [ci skip]" || true
            git push git@github.com:NUVR/nuvr.github.io.git master
