# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "95:40:ac:cd:b4:2e:84:17:df:34:66:bb:f8:3b:d5:f9"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Remove old builds
          command: |
            rm -rf assets/ styles/
            # Ignore errors if doesn't exist
            if [ -e index.html ]; then
                rm index.html
            fi

      - run:
          name: Build files
          command: yarn deploy

      - run:
          name: Deploy files to GitHub
          command: |
            # Set Git username if not already set
            if [ ! "(git config --list | grep -q user.name)" ]; then
                git config --global user.name "CircleCI"
                git config --global user.email "circleci@nuvr.io"
            fi

            git add .
            git commit -m "Update site (`date '+%F %T %Z'`) [ci skip]" || true
            git push git@github.com:NUVR/nuvr.github.io.git master
